export const Categories: string[] = [
  "Technology",
  "Travel",
  "Food",
  "Health & Wellness",
  "Finance",
  "Books & Literature",
  "Movies & TV Shows",
  "Gaming",
  "Music",
  "Art & Design",
  "Science",
  "Home & Garden",
  "Fashion & Style",
  "Photography",
  "Sports",
  "Education",
  "DIY & Crafts",
  "Parenting & Family",
  "History",
  "Animals & Pets",
];
